---
- name: Install nginx and start the service.
  hosts: all
  become: Yes

  tasks: 
   - name: installing nginx
     apt:
       name: nginx
       state: present

   - name: Start nginx service
     service:
       name: nginx
       state: started
       enabled: True


